### ISSUE TITLE
missing patch.o?

### ISSUE THREAD

**Issue by ewwink** [scumjr/highball#1]
is `patch.o` auto generated or missing from repo?

```
# make
protoc -I=proto/ --cpp_out=proto/ proto/soda_api.proto
g++ -c -o proto/soda_api.pb.o proto/soda_api.pb.cc
g++ -c -o highball.o highball.c -I. -Wall
make: *** No rule to make target 'patch.o', needed by 'highball'.  Stop.
```

**Comment by scumjr** [comment]
Hello,

As mentioned in the [blogpost](https://scumjr.github.io/2023/04/27/automatic-subtitles-with-soda/#bypassing-protections), it is [left](https://github.com/biemster/gasr/issues/5) as an exercise to the reader for various reasons.

**Comment by ewwink** [comment]
Oh I see, Thanks.
